---
- name: install docker
  hosts: localhost
  become: true

  tasks:
          - name: Remove old docker and dependencies
            apt:
                    name: 
                         - docker 
                         - docker-engine 
                         - docker.io
                    state: absent
            ignore_errors: yes

          - name: ubuntu update
            apt:
                    update_cache: yes

          - name: install docker
            shell: apt install docker.io -y
         
          - name: install docker dependencies
            shell: snap install docker
